name: ochan
version: '0.1.0'
synopsis: Owned channels in the Ownership Monad
description: Resource tracking channels that use the rules enforced in the Ownership Monad.
category: Concurrency
author: Mike McGirr
maintainer: mike@oatsmail.com
copyright: 2017 Mike McGirr
license: BSD3
github: lambda-land/OwnershipMonad
extra-source-files:
  - README.md
  - CHANGELOG.md

dependencies:
  - base >=4.8 && <5
  - oref >= 0.0.3
  - mtl == 2.2.1
  - transformers
  # for the tests
  - async
  - text
  - bytestring

library:
  source-dirs: src
  ghc-options: -Wall
  exposed-modules:
    - Control.Concurrent.OChan

# Test suite
tests:
  test:
    main: Main.hs
    ghc-options:
      - -Wall
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    source-dirs:
      - src
      - test
