name: ochan
version: '0.1.0.0'
synopsis: Owned channels
description: Resource tracking channels
category: Concurrency
author: Mike McGirr
maintainer: mcgirrm@oregonstate.edu
copyright: 2017 Mike McGirr
license: BSD3
github: lambda-land/OwnershipMonad
extra-source-files:
  - README.md

dependencies:
  - base >=4.7 && <5
  - mtl
  - oref

library:
  source-dirs: src
  ghc-options: -Wall
  exposed-modules:
    - Control.Concurrent.OChan

# Test suite
tests:
  test:
    main: Spec.hs
    source-dirs:
      - src
      - test
    ghc-options:
      - -Wall
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
