name: oref
version: '0.0.3'
synopsis: Owned references in the Ownership Monad
description: A monad which implements aspects of the Rust langauge's ownership system as a library in Haskell.
category: Data
author: Mike McGirr
maintainer: mike@oatsmail.com
copyright: 2017 Mike McGirr
license: BSD3
github: lambda-land/OwnershipMonad
extra-source-files:
  - README.md
  - CHANGELOG.md

default-extensions:
  - ExistentialQuantification

ghc-options:
  - -Wall
  - -Wredundant-constraints

dependencies:
  - base >= 4.8 && < 5
  - containers
  - mtl == 2.2.1
  - transformers
  - either

library:
  source-dirs: src
  exposed-modules:
    - Data.ORef
    - Data.ORef.Internal

# Test suite
tests:
  test:
    main: Main.hs
    ghc-options: -Wall
    source-dirs:
      - src
      - test
