# Stack configuration file:
# http://docs.haskellstack.org/en/stable/yaml_configuration/

# The resolver determines which packages are used to resolve the dependencies
# in the Cabal build file.
resolver: lts-8.23

nix:
  enable: true
  shell-file: shell.nix
